# Pruebas Examen Ej3

###
# @name getAllRatones
GET http://localhost:8081/api/ratones
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmVzIiwiZXhwIjoxNzA4OTc2NzY0LCJ1c2VyIjoiaW5lcyIsInJvbCI6IkFETUlOIn0.FRhu1wtdImrs6NaVgqITT2fWPMqHLX0XwiKmmcJf4PizZqZv6eLAKY_qV4nekyC8EHNDadd2v4ZROd-IqAYM_00Pty781YilnmbxuMV0-fDPp7om-uTgWlAbT_y8-mR9rHCDD9HSUDI3XB5sfKqc7eYheDGHJPo9o34lZrxCr_rdzYbS2tJq2-6Ib1GiBQYQUl-OWB1G8jX2KE4t17pC2tYfr9byach3CG35QHOnkJQeWHnfCSM6rmH0yhVxIm5smwDoejNqZdsRzjDdCAqXKzJ1b9DOX0jV6SoAMUjUJyoildrmwsq-vVs7P61BW8mX1kL2HlP2jFAbwuX3O46HHQ

###
# @name addRaton
POST http://localhost:8081/api/ratones
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmVzIiwiZXhwIjoxNzA4OTc2NzY0LCJ1c2VyIjoiaW5lcyIsInJvbCI6IkFETUlOIn0.FRhu1wtdImrs6NaVgqITT2fWPMqHLX0XwiKmmcJf4PizZqZv6eLAKY_qV4nekyC8EHNDadd2v4ZROd-IqAYM_00Pty781YilnmbxuMV0-fDPp7om-uTgWlAbT_y8-mR9rHCDD9HSUDI3XB5sfKqc7eYheDGHJPo9o34lZrxCr_rdzYbS2tJq2-6Ib1GiBQYQUl-OWB1G8jX2KE4t17pC2tYfr9byach3CG35QHOnkJQeWHnfCSM6rmH0yhVxIm5smwDoejNqZdsRzjDdCAqXKzJ1b9DOX0jV6SoAMUjUJyoildrmwsq-vVs7P61BW8mX1kL2HlP2jFAbwuX3O46HHQ
Content-Type: application/json

{
  "nombre": "Lucas",
  "edad": 2
}

###
# @name loginInes
GET http://localhost:8081/login?
    username=ines&
    password=ines

###
# @name loginPepe
GET http://localhost:8081/login?
    username=pepe&
    password=ines

###
# @name loginLucas
GET http://localhost:8081/login?
    username=lucas&
    password=ines

### getInformeById
GET http://localhost:8081/api/informes?id=2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmVzIiwiZXhwIjoxNzA4OTg4Mjc4LCJ1c2VyIjoiaW5lcyIsInJvbCI6IkFETUlOIn0.WtNZd7Qh_pNlwa-GXqTLllOfX_pmajm2bUVxefPBVMcuK1f8uxXOhwdjfZjePJzXJIfP4bbfd55dGcuN9NHqt0SWrWrwSncQ1cJRHQXouY-mdbNGq5FCRE4e1yY_D589ogMQhdIQI5OQMZxDBSM10lJZglSbj4EuekUu4qfYFQom05oR4gNSn5VfzKNR2j0TQgzQfx3fEOkSBcatvgRUj4Qq536Yl20bqjJmvE8JN9N4MY0DfdA1a766KXtEiDJUr-HEBHypKL92R8D5Pp4pkDxux8N6hFIvehvP_j6FZfMThiRaHx8YR8mZni4EM5LzTinV3POJgQfOwPezvLYp2w

###
# @name getAllInformesByRol
GET http://localhost:8081/api/informesrol?
    rol=NIVEL1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmVzIiwiZXhwIjoxNzA4OTc2NzY0LCJ1c2VyIjoiaW5lcyIsInJvbCI6IkFETUlOIn0.FRhu1wtdImrs6NaVgqITT2fWPMqHLX0XwiKmmcJf4PizZqZv6eLAKY_qV4nekyC8EHNDadd2v4ZROd-IqAYM_00Pty781YilnmbxuMV0-fDPp7om-uTgWlAbT_y8-mR9rHCDD9HSUDI3XB5sfKqc7eYheDGHJPo9o34lZrxCr_rdzYbS2tJq2-6Ib1GiBQYQUl-OWB1G8jX2KE4t17pC2tYfr9byach3CG35QHOnkJQeWHnfCSM6rmH0yhVxIm5smwDoejNqZdsRzjDdCAqXKzJ1b9DOX0jV6SoAMUjUJyoildrmwsq-vVs7P61BW8mX1kL2HlP2jFAbwuX3O46HHQ

###
# @name addInforme
POST http://localhost:8081/api/addinforme
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJpbmVzIiwiZXhwIjoxNzA4OTc2NzY0LCJ1c2VyIjoiaW5lcyIsInJvbCI6IkFETUlOIn0.FRhu1wtdImrs6NaVgqITT2fWPMqHLX0XwiKmmcJf4PizZqZv6eLAKY_qV4nekyC8EHNDadd2v4ZROd-IqAYM_00Pty781YilnmbxuMV0-fDPp7om-uTgWlAbT_y8-mR9rHCDD9HSUDI3XB5sfKqc7eYheDGHJPo9o34lZrxCr_rdzYbS2tJq2-6Ib1GiBQYQUl-OWB1G8jX2KE4t17pC2tYfr9byach3CG35QHOnkJQeWHnfCSM6rmH0yhVxIm5smwDoejNqZdsRzjDdCAqXKzJ1b9DOX0jV6SoAMUjUJyoildrmwsq-vVs7P61BW8mX1kL2HlP2jFAbwuX3O46HHQ

{
  "nombre": "Nuevo Informe",
  "fecha": "2000-01-01",
  "rol": "NIVEL1"
}
