# Pruebas Examen Ej1

###
# @name getAlumnosAnidado
GRAPHQL http://localhost:8080/graphql

query {
    getAlumnos{
        nombre
        asignaturas{
            nombre
            nota
        }
    }
}

###
# @name addAlumnoNombre
GRAPHQL http://localhost:8080/graphql

mutation addAlumno{
    addAlumno(nombre: "nuevo"){
        nombre
    }
}

###
# @name getAlumnosNombre
GRAPHQL http://localhost:8080/graphql

query {
    getAlumnos{
        nombre
    }
}
